#theme: jekyll-theme-cayman
title: Academic Website of Shohei KOJIMA
#description: Welcome!

owner:
    name: Shohei Kojima
    bio: 'test'

highlight-color: '#CC0000'
lowlight-color: '#000'


navbar:
    right:
      - text: "Home"
        href: index.md
