#theme: jekyll-theme-cayman
title: Academic Website of Shohei KOJIMA
#description: Welcome!

theme: theme.css

highlight-color: '#CC0000'
lowlight-color: '#000'


navbar:
    right:
        - text: "Home"
          href: index.md
        - text: "Publication"
          href: publication.md
